module.exports=(sequlize,Sequelize)=>{
    const user=sequlize.define("User",{
        id:{
            type:Sequelize.INTEGER,
            primaryKey:true,
            autoIncrement:true
        },
        username:{
            type:Sequelize.STRING,
            allowNull:false
        },
        password:{
            type:Sequelize.STRING,
            allowNull:false
        },
        email:{
            type:Sequelize.STRING,
            allowNull:false,
            unique:true
        },
        mobile:{
            type:Sequelize.STRING,
            allowNull:false,
            unique:true
        },
        isVerified:{
            type:Sequelize.BOOLEAN,
            defaultValue:false
        }
    }
    )
    return user;
}